### ISSUE TITLE
Add grade_received field to course review

### ISSUE THREAD

**Issue by mattdahl** [aspc/mainsite#80]
There should be a field for the user to (optionally) tell us what grade he got in the class that he's reviewing. We should then display that alongside his review, and also display an average grade for a section.

**Comment by frozenpandaman** [comment]
Considering professors have wildly different grading styles, I don't think this feature would be particularly beneficial, especially if we want to support the philosophy of taking classes out of interest rather than for grades, or only if you'll get a good grade. (I think most people can ask around to find out information about specific course grading if they really need.) Just my two cents.

I do, however, think bringing back those rating sub-divisions would be extremely useful!

@mattdahl

**Comment by ZiqiXiong** [comment]
I beg to differ here. "Considering professors have wildly different grading styles, I don't think this feature would be particularly beneficial" I think the average grading will be based on course and instructor, which means the grading represents unbiasedly what grade you will likely receive in the section. The fact that professors have drastically different grading styles is exactly the reason that the grading information is valuable. If they all follow a standard criterion, then there is no point keeping the info.
