### ISSUE TITLE
Upgrade FB Graph API calls to v2.1+

### ISSUE THREAD

**Issue by mattdahl** [aspc/mainsite#99]
5C Ride Share (and maybe other apps too) need to be upgraded:

> 5C Ride Share has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences.
> 
> We recommend using our new Graph API Upgrade Tool to see which of your calls are affected by this change as well as any replacement calls in newer versions. You can also use our changelog to see the full list of changes.

**Comment by thebradbain** [comment]
It looks like the underlying issue here has to do with the versioning of 'omniauth' and 'omniauth-facebook': upgrading omniauth-facebook to version 4.0.0 (from 2.0.0) fixes the auth problem, but it seems 'omniauth' cannot properly handle the upgrade without being upgraded to 1.6.1 (from 1.2.2) [see [https://github.com/omniauth/omniauth/issues/872](https://github.com/omniauth/omniauth/issues/872)]... which would require we update the version of ruby we're using to at least 2.1.9 and thus the version of rails to >= 4.0, which opens up a whole different set of problems.

**Comment by KentShikama** [comment]
I don't see any issue with upgrading ruby and rails as we barely have any dependencies - if we even have any other - that rely on them. Our rideshare app is coded in rails but that is a totally different application.

**Comment by thebradbain** [comment]
See PR #172
